algoritmo "Soma de dois numeros inteiros"

var

   //Declaração de variavéis:
   
   a,b,c:Inteiro
   
inicio

   //Realizando entradas de dados:
   Escreva("Digite um numero: ")
      Leia(a)
   Escreva("Digite mais um numero: ")
      Leia(b)
     
   //Codigo de processamento da soma dos valores das variavéis:
   c <- a+b
   
   //Codigos de saida de dados:
   Escreva("O resultado será de: ",c)
   
fimalgoritmo